#include "include/ip.h"
#include "include/icmp.h"
#include "include/arpcache.h"
#include "include/rtable.h"
#include "include/arp.h"
#include "include/log.h"
// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	// fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	rt_entry_t *entry = NULL;
	rt_entry_t *best_entry = NULL;
	u32 max_mask = 0;
	list_for_each_entry(entry, &rtable, list) {
		if ((dst & entry->mask) == (entry->dest & entry->mask)) {
			if (entry->mask > max_mask) {
				max_mask = entry->mask;
				best_entry = entry;
			}
		}
	}
	return best_entry;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	// fprintf(stderr, "TODO: send ip packet.\n");
	struct iphdr *ip_hdr = packet_to_ip_hdr(packet);
	u32 destip = ntohl(ip_hdr->daddr);
	rt_entry_t *entry = longest_prefix_match(destip);
	if (!entry) {
        log(ERROR, "no route for " IP_FMT ", drop packet\n", HOST_IP_FMT_STR(destip));
        free(packet);
        return;
    }

    if (entry->gw) {
        log(DEBUG, "send ip packet to gateway " IP_FMT "\n", HOST_IP_FMT_STR(entry->gw));
        iface_send_packet_by_arp(entry->iface, entry->gw, packet, len);
    } else {
        log(DEBUG, "send ip packet to destination " IP_FMT "\n", HOST_IP_FMT_STR(destip));
        log(DEBUG, "entry iface: %s\n", entry->iface->name);
        iface_send_packet_by_arp(entry->iface, destip, packet, len);
    }
}